/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LearningBankRouteImport } from './routes/learning-bank'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearningBankSlugRouteImport } from './routes/learning-bank.$slug'

const LearningBankRoute = LearningBankRouteImport.update({
  id: '/learning-bank',
  path: '/learning-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningBankSlugRoute = LearningBankSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LearningBankRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learning-bank': typeof LearningBankRouteWithChildren
  '/learning-bank/$slug': typeof LearningBankSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learning-bank': typeof LearningBankRouteWithChildren
  '/learning-bank/$slug': typeof LearningBankSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learning-bank': typeof LearningBankRouteWithChildren
  '/learning-bank/$slug': typeof LearningBankSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/learning-bank' | '/learning-bank/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/learning-bank' | '/learning-bank/$slug'
  id: '__root__' | '/' | '/learning-bank' | '/learning-bank/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearningBankRoute: typeof LearningBankRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/learning-bank': {
      id: '/learning-bank'
      path: '/learning-bank'
      fullPath: '/learning-bank'
      preLoaderRoute: typeof LearningBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-bank/$slug': {
      id: '/learning-bank/$slug'
      path: '/$slug'
      fullPath: '/learning-bank/$slug'
      preLoaderRoute: typeof LearningBankSlugRouteImport
      parentRoute: typeof LearningBankRoute
    }
  }
}

interface LearningBankRouteChildren {
  LearningBankSlugRoute: typeof LearningBankSlugRoute
}

const LearningBankRouteChildren: LearningBankRouteChildren = {
  LearningBankSlugRoute: LearningBankSlugRoute,
}

const LearningBankRouteWithChildren = LearningBankRoute._addFileChildren(
  LearningBankRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearningBankRoute: LearningBankRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
